# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-01 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='frist_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='contactbook.Person'),
        ),
    ]
